config/routes.rb
Rails.application.routes.draw do
  resources :works

  root 'welcome#index'
  get 'about' => 'welcome#about'
  get 'contact' => 'welcome#contact'
  get 'map' => 'welcome#map'
  get 'sections' => 'welcome#sections'
  get 'works' => 'works#index'
  
  

end

app/models/work.rb
class Work < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def about
  end

  def contact
  end

  def works
  end

  def map
  end

  def sections
  end
end

app/controllers/works_controller.rb
class WorksController < ApplicationController
  before_action :set_work, only: [:show, :edit, :update, :destroy]

  # GET /works
  # GET /works.json
  def index
    @works = Work.all
  end

  # GET /works/1
  # GET /works/1.json
  def show
  end

  # GET /works/new
  def new
    @work = Work.new
  end

  # GET /works/1/edit
  def edit
  end

  # POST /works
  # POST /works.json
  def create
    @work = Work.new(work_params)

    respond_to do |format|
      if @work.save
        format.html { redirect_to @work, notice: 'Work was successfully created.' }
        format.json { render :show, status: :created, location: @work }
      else
        format.html { render :new }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /works/1
  # PATCH/PUT /works/1.json
  def update
    respond_to do |format|
      if @work.update(work_params)
        format.html { redirect_to @work, notice: 'Work was successfully updated.' }
        format.json { render :show, status: :ok, location: @work }
      else
        format.html { render :edit }
        format.json { render json: @work.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /works/1
  # DELETE /works/1.json
  def destroy
    @work.destroy
    respond_to do |format|
      format.html { redirect_to works_url, notice: 'Work was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_work
      @work = Work.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def work_params
      params.require(:work).permit(:title, :description, :site_url, :github_url)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/helpers/works_helper.rb
module WorksHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
<title>GA_AT</title>

  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/css/bootstrap.min.css">
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.0/js/bootstrap.min.js"></script>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
<style>
     body {
        background: url(<%= asset_path "winter_trees_sky.jpg" %>) 
        no-repeat;
        background-size: cover;
        


    }  
    .container {
        background: rgba(255,255,255,1);
    }
</style>
</head>
<body>

  <nav class="navbar navbar-default">
  <!-- <div class="container-fluid"> -->
    <!-- Brand and toggle get grouped for better mobile display -->
    <!-- <div class="navbar-header"> -->
      <!-- <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button> -->
      <a class="navbar-brand" <%= link_to 'Home', '/' %></a>
    </div>
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <li><%= link_to 'About', about_path %><span class="sr-only">(current)</span></a></li>
        <li><%= link_to 'Contact', contact_path %></li>
        <li><%= link_to 'Portfolio', works_path %></li>
        <li><%= link_to 'Sections', sections_path %></li>
        <li><%= link_to 'Map', map_path %></li>
        <!-- <li><a href="#">Link</a></li> -->
        <!-- <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a> -->
          <!-- <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li>
            <li class="divider"></li>
            <li><a href="#">One more separated link</a></li>
          </ul> -->
        <!-- </li>
      </ul> -->
      <!-- <form class="navbar-form navbar-left" role="search">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Search">
        </div>
        <button type="submit" class="btn btn-default">Submit</button>
      </form> -->
      <!-- <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Link</a></li>
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false">Dropdown <span class="caret"></span></a>
          <ul class="dropdown-menu" role="menu">
            <li><a href="#">Action</a></li>
            <li><a href="#">Another action</a></li>
            <li><a href="#">Something else here</a></li>
            <li class="divider"></li>
            <li><a href="#">Separated link</a></li> -->
          </ul>
        </li>
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>
<!-- <ul class="nav nav-pills" >
  <li class="active">

    <%= link_to 'Home', '/' %></li>
    <li><%= link_to 'About', about_path %></li>
    <li><%= link_to 'Contact', contact_path %></li> 
    <li><%= link_to 'Portfolio', works_path %></li> 
    <li><%= link_to 'Sections', sections_path %></li>
</ul> -->
<br/>
  <div class="container">
    <%= yield %>
  </div>
</body>
</html>

app/views/welcome/about.html.erb
</br>

  <head>
    <title>GeorgiaAT</title>
    <style>
    /*h1 {
          font-size:50px;
          text-align: center;
        }
    h2 { font-size: 45px;
         text-align: center;
         font-style: italic;
        }
    #html body {
        height: 100%;
        width: 100%;
        padding: 0;
        margin: 0;
    }*/
    /*#full-screen-background-image {
          z-index: -999;
          min-height: 100%;
          min-width: 1024px;
          width: 100%;
          height: auto;
          position: fixed;
          top: 0;
          left: 0;
          opacity: 0.5;
         }
    #wrapper {
          position: relative;
          width: 800px;
          min-height: 400px;
          margin: 100px auto;
          color: #333;
    }*/
    /*p {
        font-size: 25px;
        font-family: Arial, Helvetica, sans-serif;
        text-align: center;
    }
    p1 {
        font-size: 25px;
        font-family: Arial, Helvetica, sans-serif;
        color:black;
    }*/
    
.img-author-photo {
        border: 2px solid;
        border-bottom-left-radius: 2em;
        border-bottom-right-radius: 2em;
        border-top-left-radius: 2em;
        border-top-right-radius: 2em;
        box-shadow: 10px 10px 5px #999999;

    }

    </style>
  </head>
 

<div id="wrapper">



<h2>Sharon Connell (aka Oma)</h2>
<img class="img-author-photo" src="<%=image_path('author_stream.jpg')%>" alt="Profile Photo" style="width:304px;height:228px"><p>
</br>
<p1>The author enjoys a full time career in addition to her jaunts in the woods with her husband (of 32+ years) Thomas and her sweet Rottweiler.</p1><p><p1>Her six adult kids and 4 grandchildren are a constant source of wonder and delight.</p1><p>




</div>



</body>

app/views/welcome/contact.html.erb
</br>

<h1>Any more information?</h1>
<p>Leave feedback that will be helpful to others.</p>

app/views/welcome/index.html.erb
<head>   
<title>GeorgiaHiking</title>
</head>
<body>
  <div id="wrapper">
</br>
<h2>Hiking The Appalachian Trail in Georgia</h2>

<h4>From Georgia With Love...</h4>

<p>Why would anyone undertake the +/- 2180 miles of the Appalachian Trail?</p> 
<p>
<p>Why sleep on the ground, go without showers, endure hour after hour of walking through the woods with the off chance of meeting a bear or snake?</p> 
<p>
<p>Through hikers (those intrepid hiker attempting the whole trail), have diverse reasons. I have met members of the military taking the opportunity before beginning their civilian lives, retirees seizing the opportunity to do something they have always dreamed of doing, college students taking a semester off, a mid-life crisis, or numerous other reasons. Each hiker has a unique story and this is one of the many things to discover along the way.</p>
<p>
<p>The Appalachian Trail travels 78.5 miles through Georgia. Springer Mountain is the southern terminus of the AT.  The Georgia portion is between 2500 feet in elevation with a high point of 4461 feet at Blood Mountain. This can be startling for those starting the hike not in the best of condition.
 </p>
<p>
 <p>The Georgia portion of the AT offers many stunning vistas and interesting flora and fauna. It is written in the hope you will not only overcome the Georgia portion, but relish it!</p><p>


</div>



</body>


    

app/views/welcome/map.html.erb
<style>
.img-map {
    border: 0px solid;
        border-bottom-left-radius: 0em;
        border-bottom-right-radius: 0em;
        border-top-left-radius: 0em;
        border-top-right-radius: 0em;
        box-shadow: 0px 0px 0px #999999;
}
</style>

<img class="img-map" src="<%=image_path('NewFerns.JPG')%>" alt="GA Appalachian Trail Map" style="width:100%;height:auto;position">

app/views/welcome/sections.html.erb
<h1>Sections</h1>
<p>This is where users will upload photos and descriptions of sections.</p>

app/views/works/_form.html.erb
<%= form_for(@work) do |f| %>
  <% if @work.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@work.errors.count, "error") %> prohibited this work from being saved:</h2>

      <ul>
      <% @work.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field form-group">
    <%= f.label :title %><br>
    <%= f.text_field :title, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :site_url %><br>
    <%= f.text_field :site_url, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :github_url %><br>
    <%= f.text_field :github_url, class: 'form-control' %>
  </div>
  <div class="field form-group">
    <%= f.label :description %><br>
    <%= f.text_field :description, class: 'form-control', rows: '5' %>
  </div>
  <div class="actions">
    <%= f.submit class: "btn btn-primary" %>
  </div>
<% end %>

app/views/works/edit.html.erb
</br>

<h1>Editing Work</h1>

<%= render 'form' %>

<%= link_to 'Show', @work %> |
<%= link_to 'Back', works_path %>

app/views/works/index.html.erb
</br>

<h1>Portfolio</h1>

  <div class="row">
    <% @works.each do |work| %>
      <div class="col-md-4">
       <div class="panel panel-default">
        <div class="panel-body">
         <h2><%= work.title %></h2>
         <h4><%= work.description %></h4>
         <h4><a href="<%= work.site_url %>" target="_blank">Live Site</a></h4>
         <h4><a href="<%= work.github_url %>" target="_blank">GitHub</a></h4>
         <a> </a>
         <div class="btn-group">
          <%= link_to 'Show', work, class: "btn btn-default" %>
          <%= link_to 'Edit', edit_work_path(work), class: "btn btn-default" %>
          <%= link_to 'Destroy', work, method: :delete, data: { confirm: 'Are you really, really sure?' }, class: "btn btn-default" %>
         </div>
        </div>
      </div>
    </div>
  <% end %>
</div>

<%= link_to 'New Work', new_work_path, class: "btn btn-primary" %>

app/views/works/new.html.erb
<h1>New Work</h1>

<%= render 'form' %>

<%= link_to 'Back', works_path %>

app/views/works/show.html.erb
</br>

<h2><%= @work.title %></h2> 

<h4><%= @work.description %></h4> 

<div class="btn-group">
  <%= link_to 'Edit', edit_work_path(@work), class: "btn btn-default" %> 
  <%= link_to 'Back', works_path, class: "btn btn-default" %>
</div>